import type { components } from './schema'

type S = components['schemas']

export type Profile = S['Profile']
export type UserRole = S['UserRole']
export type UserRead = S['UserRead']
export type BuildingRead = S['BuildingRead']
export type ApartmentRead = S['ApartmentRead']
export type ApartmentDetail = S['ApartmentDetail']
export type MeterRead = S['MeterRead']
export type MeterKind = S['MeterKind']
export type ReadingRead = S['ReadingRead']
export type ReadingJournalItem = S['ReadingJournalItem']
export type ReadingSource = S['ReadingSource']
export type TariffRead = S['TariffRead']
export type TariffMethod = S['TariffMethod']
export type InvoiceRead = S['InvoiceRead']
export type InvoiceDetail = S['InvoiceDetail']
export type InvoiceStatus = S['InvoiceStatus']
export type CalculationBasis = S['CalculationBasis']
export type PaymentRead = S['PaymentRead']
export type PaymentMethod = S['PaymentMethod']
export type DebtorRow = S['DebtorRow']
export type TicketRead = S['TicketRead']
export type TicketDetail = S['TicketDetail']
export type TicketStatus = S['TicketStatus']
export type TicketCategory = S['TicketCategory']
export type TicketPriority = S['TicketPriority']
export type PassRead = S['PassRead']
export type PassDetail = S['PassDetail']
export type PassCheckResult = S['PassCheckResult']
export type PassKind = S['PassKind']
export type AnnouncementRead = S['AnnouncementRead']
export type Dashboard = S['Dashboard']
export type ApiKeyRead = S['ApiKeyRead']
export type DataSourceRead = S['DataSourceRead']
export type SyncResult = S['SyncResult']
