"""initial schema

Revision ID: 511d2bd2e565
Revises:
Create Date: 2026-10-05 15:41:18.725549

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "511d2bd2e565"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("floors", sa.Integer(), nullable=True),
        sa.Column("entrances", sa.Integer(), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
        sa.UniqueConstraint("address", name=op.f("uq_buildings_address")),
    )
    op.create_table(
        "meter_data_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("http_json", name="providerkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("auth_token", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("cursor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=32), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_data_sources")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "manager",
                "accountant",
                "security",
                "resident",
                name="userrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_announcements_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_announcements_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
    )
    op.create_index(
        op.f("ix_announcements_building_id"), "announcements", ["building_id"], unique=False
    )
    op.create_index(
        op.f("ix_announcements_published_at"), "announcements", ["published_at"], unique=False
    )
    op.create_table(
        "apartments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("account_number", sa.String(length=32), nullable=False),
        sa.Column("area", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("residents_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("area > 0", name=op.f("ck_apartments_area_positive")),
        sa.CheckConstraint(
            "residents_count >= 0", name=op.f("ck_apartments_residents_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_apartments_building_id_buildings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apartments")),
        sa.UniqueConstraint("account_number", name=op.f("uq_apartments_account_number")),
        sa.UniqueConstraint("building_id", "number", name=op.f("uq_apartments_building_id_number")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_api_keys_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index(op.f("ix_api_keys_prefix"), "api_keys", ["prefix"], unique=False)
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "per_area",
                "per_resident",
                "metered",
                "fixed",
                name="tariffmethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "meter_kind",
            sa.Enum(
                "cold_water",
                "hot_water",
                "electricity",
                "heating",
                "gas",
                name="meterkind",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("normative", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method <> 'metered' OR meter_kind IS NOT NULL", name=op.f("ck_tariffs_metered_kind")
        ),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_tariffs_rate_non_negative")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name=op.f("ck_tariffs_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_tariffs_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_index(op.f("ix_tariffs_building_id"), "tariffs", ["building_id"], unique=False)
    op.create_table(
        "apartment_residents",
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_apartment_residents_apartment_id_apartments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_apartment_residents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("apartment_id", "user_id", name=op.f("pk_apartment_residents")),
    )
    op.create_index(
        op.f("ix_apartment_residents_user_id"), "apartment_residents", ["user_id"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "issued",
                "partially_paid",
                "paid",
                "cancelled",
                name="invoicestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "opening_balance", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "paid_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM period) = 1", name=op.f("ck_invoices_period_first_day")
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_invoices_apartment_id_apartments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_invoices_number")),
    )
    op.create_index(op.f("ix_invoices_apartment_id"), "invoices", ["apartment_id"], unique=False)
    op.create_index(op.f("ix_invoices_period"), "invoices", ["period"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(
        "uq_invoices_apartment_period_active",
        "invoices",
        ["apartment_id", "period"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelled'"),
    )
    op.create_table(
        "meters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "cold_water",
                "hot_water",
                "electricity",
                "heating",
                "gas",
                name="meterkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("serial_number", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("installed_at", sa.Date(), nullable=True),
        sa.Column("verification_due", sa.Date(), nullable=True),
        sa.Column(
            "initial_value", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_meters_apartment_id_apartments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meters")),
        sa.UniqueConstraint("external_id", name=op.f("uq_meters_external_id")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_meters_serial_number")),
    )
    op.create_index(op.f("ix_meters_apartment_id"), "meters", ["apartment_id"], unique=False)
    op.create_index(
        op.f("ix_meters_verification_due"), "meters", ["verification_due"], unique=False
    )
    op.create_table(
        "passes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("guest", "vehicle", "delivery", name="passkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("visitor_name", sa.String(length=255), nullable=True),
        sa.Column("vehicle_plate", sa.String(length=16), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_one_time", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "rejected",
                "used",
                "cancelled",
                name="passstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("valid_until > valid_from", name=op.f("ck_passes_valid_range")),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_passes_apartment_id_apartments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_passes_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_passes_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passes")),
        sa.UniqueConstraint("code", name=op.f("uq_passes_code")),
    )
    op.create_index(op.f("ix_passes_apartment_id"), "passes", ["apartment_id"], unique=False)
    op.create_index(op.f("ix_passes_status"), "passes", ["status"], unique=False)
    op.create_index(op.f("ix_passes_valid_until"), "passes", ["valid_until"], unique=False)
    op.create_index(op.f("ix_passes_vehicle_plate"), "passes", ["vehicle_plate"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "bank", "card", "cash", "other", name="paymentmethod", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_payments_apartment_id_apartments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_payments_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("reference", name=op.f("uq_payments_reference")),
    )
    op.create_index(op.f("ix_payments_apartment_id"), "payments", ["apartment_id"], unique=False)
    op.create_index(op.f("ix_payments_paid_at"), "payments", ["paid_at"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "plumbing",
                "electricity",
                "heating",
                "elevator",
                "cleaning",
                "territory",
                "intercom",
                "complaint",
                "other",
                name="ticketcategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                "emergency",
                name="ticketpriority",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "in_progress",
                "waiting",
                "resolved",
                "closed",
                "rejected",
                name="ticketstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("rating_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_tickets_rating_range")),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
            name=op.f("fk_tickets_apartment_id_apartments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tickets_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_tickets_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_tickets_building_id_buildings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(op.f("ix_tickets_apartment_id"), "tickets", ["apartment_id"], unique=False)
    op.create_index(op.f("ix_tickets_assignee_id"), "tickets", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_tickets_building_id"), "tickets", ["building_id"], unique=False)
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("tariff_id", sa.Integer(), nullable=True),
        sa.Column("meter_id", sa.Integer(), nullable=True),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "basis",
            sa.Enum(
                "tariff",
                "meter",
                "average",
                "normative",
                "recalculation",
                name="calculationbasis",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reading_from", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("reading_to", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_lines_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meters.id"],
            name=op.f("fk_invoice_lines_meter_id_meters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariffs.id"],
            name=op.f("fk_invoice_lines_tariff_id_tariffs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
    )
    op.create_index(
        op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"], unique=False
    )
    op.create_index(op.f("ix_invoice_lines_meter_id"), "invoice_lines", ["meter_id"], unique=False)
    op.create_table(
        "meter_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meter_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "resident",
                "staff",
                "api",
                "provider",
                name="readingsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meter_id"],
            ["meters.id"],
            name=op.f("fk_meter_readings_meter_id_meters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_meter_readings_submitted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_readings")),
        sa.UniqueConstraint(
            "meter_id", "taken_at", name=op.f("uq_meter_readings_meter_id_taken_at")
        ),
    )
    op.create_index(
        op.f("ix_meter_readings_taken_at"), "meter_readings", ["taken_at"], unique=False
    )
    op.create_table(
        "pass_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pass_id", sa.Integer(), nullable=False),
        sa.Column("checked_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "entered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["checked_by_id"],
            ["users.id"],
            name=op.f("fk_pass_visits_checked_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pass_id"],
            ["passes.id"],
            name=op.f("fk_pass_visits_pass_id_passes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pass_visits")),
    )
    op.create_index(op.f("ix_pass_visits_pass_id"), "pass_visits", ["pass_id"], unique=False)
    op.create_table(
        "ticket_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_ticket_comments_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ticket_comments_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_comments")),
    )
    op.create_index(
        op.f("ix_ticket_comments_ticket_id"), "ticket_comments", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_comments_ticket_id"), table_name="ticket_comments")
    op.drop_table("ticket_comments")
    op.drop_index(op.f("ix_pass_visits_pass_id"), table_name="pass_visits")
    op.drop_table("pass_visits")
    op.drop_index(op.f("ix_meter_readings_taken_at"), table_name="meter_readings")
    op.drop_table("meter_readings")
    op.drop_index(op.f("ix_invoice_lines_meter_id"), table_name="invoice_lines")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_building_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_assignee_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_apartment_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_payments_paid_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_apartment_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_passes_vehicle_plate"), table_name="passes")
    op.drop_index(op.f("ix_passes_valid_until"), table_name="passes")
    op.drop_index(op.f("ix_passes_status"), table_name="passes")
    op.drop_index(op.f("ix_passes_apartment_id"), table_name="passes")
    op.drop_table("passes")
    op.drop_index(op.f("ix_meters_verification_due"), table_name="meters")
    op.drop_index(op.f("ix_meters_apartment_id"), table_name="meters")
    op.drop_table("meters")
    op.drop_index(
        "uq_invoices_apartment_period_active",
        table_name="invoices",
        postgresql_where=sa.text("status <> 'cancelled'"),
    )
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_period"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_apartment_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_apartment_residents_user_id"), table_name="apartment_residents")
    op.drop_table("apartment_residents")
    op.drop_index(op.f("ix_tariffs_building_id"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index(op.f("ix_api_keys_prefix"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("apartments")
    op.drop_index(op.f("ix_announcements_published_at"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_building_id"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_table("meter_data_sources")
    op.drop_table("buildings")
    # ### end Alembic commands ###
